ajout fonction protocol NetworkService
Nathan765/HoloDex pull request #9
Opened 2024-11-24 13:52 UTC by Adrien8989

2024-12-01 13:54 UTC, Nathan765 requested changes

2024-12-01 13:54 UTC, Nathan765 commented on HoloDex/Infrastructure/Network/Service/CardDetailsNetworkServiceImpl.swift
> -        provider.request(target: .getCard(id: cardId, select: select)) { result in
ça ne fonctionne pas ..

2024-12-01 14:12 UTC, Nathan765 requested changes
Inversion

2024-12-01 17:01 UTC, Adrien8989 commented on HoloDex/Presentation/CardDetailsViewModel.swift
> +        networkService.request<CardDetailsAPIResponse>(target: PokemonTcgApi.getCard(id: cardId, select: select)) { result in
donc CardDetailsNetworkServiceImpl il a un protocol aussi ? avec fetchCardDetails comme fonction ? + la fonction Request du NetworkService ?

2024-12-01 17:01 UTC, Adrien8989 commented on HoloDex/Infrastructure/Network/Service/CardDetailsNetworkServiceImpl.swift
> -        provider.request(target: .getCard(id: cardId, select: select)) { result in
donc il hérite pas de NetworkService ? ou il faut la fonction Request en plus de FetchCardDetails ?

2024-12-04 15:13 UTC, Nathan765 commented on HoloDex/Infrastructure/Network/Service/CardDetailsNetworkServiceImpl.swift
> -        provider.request(target: .getCard(id: cardId, select: select)) { result in
NetworkService --> ce sont les implémentation de clients API qui doivent se conformer (ex: Moya, Alamofire, UrlSession ou custom)

Ton service `CardDetailsNetworkServiceImpl` lui ne doit pas s'y conformer dans notre cas d'usage  il se focus sur le quoi et pas le comment.

quoi = CardDetails
comment = networkService.request(_:)

2024-12-04 15:14 UTC, Nathan765 commented on HoloDex/Presentation/CardDetailsViewModel.swift
> +        networkService.request<CardDetailsAPIResponse>(target: PokemonTcgApi.getCard(id: cardId, select: select)) { result in
> donc CardDetailsNetworkServiceImpl il a un protocol aussi ? avec fetchCardDetails comme fonction ? 

Oui

2024-12-04 21:15 UTC, Nathan765 commented on HoloDex/Infrastructure/Network/Service/CardDetailsNetworkServiceImpl.swift
> +    let provider = MoyaNetworkServiceImpl()
let networkService: NetworkService = MoyaNetworkServiceImpl()

2024-12-04 21:18 UTC, Nathan765 commented on HoloDex/Data/Network/NetworkService.swift
> +import Moya
Normalement on devrait pas avoir un import de Moya mais c'est plus simple pour le moment.

Notre protocol devrait-être agnostique de la techno mais pour ça il faudrait passer par un endPoint custom qui serait utiliser par n'importe quel impl

2024-12-04 22:24 UTC, Nathan765 approved these changes

2024-12-04 22:25 UTC, merged